name: Deployment pipeline

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: Jest Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: E2E Test
        if: success()
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Install Vercel CLI
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  notify:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: cancelled()
        with:
          severity: warn
          details: Test Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
